vin_robot_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
    - ee_to_cone_tip
    - cone_tip_to_sphere
    - my_eff
  gains:
    shoulder_pan_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder_lift_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ee_to_cone_tip:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    cone_tip_to_sphere:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    my_eff:
      p: 100
      d: 1
      i: 1
      i_clamp: 1